//! Dispatch tables of the unversioned VPX plugin API (vpinball before
//! `595d1fd`, 2026-09-05), generated by `bindgen` from
//! `third_party/vpx-plugin-headers-v0/`.
//!
//! Only `MsgPluginAPI`, `VPXPluginAPI` and `LoggingPluginAPI` are generated
//! here. The types they reference come from the current bindings through the
//! glob import below: the pointed-to structs did not change between the two
//! header sets, and sharing them lets the compiler check every function
//! signature when `host_api` converts a legacy table.

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]
#![allow(clippy::all)]

#[allow(unused_imports)]
use super::vpx_sys::*;

include!(concat!(env!("OUT_DIR"), "/vpx_bindings_v0.rs"));
