//! Raw VPX plugin API bindings, generated by `bindgen` against
//! `../vpinball/plugins/plugins/{MsgPlugin,VPXPlugin,LoggingPlugin}.h`.
//!
//! All FFI types live here; safe wrappers go in sibling modules.

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]
#![allow(clippy::all)]

include!(concat!(env!("OUT_DIR"), "/vpx_bindings.rs"));
