//! Hand-fixed anchor calibration for the plugin.
//!
//! `anchor_fixed.json` (generated by `tools/anchor/lines_to_fixed.py` from
//! the annotator's validated lines) pins the cabinet anchor without running
//! the detection model — the reliable path while the model generalizes, and
//! the only path in IR tracking mode (the anchor model wants RGB frames,
//! which don't stream then).
//!
//! Search order:
//! 1. `<vpx_path>/plugins/headtracking/anchor_fixed.json` — next to the
//!    plugin library, the sibling of `plugin.cfg`;
//! 2. `<pref_path>/anchor_fixed.json` — VPX's per-user preference folder.
//!
//! Key matching: exact backend slug first (`kinect-v2`, `kinect-v1`);
//! webcams fall back to the plain `webcam` key, because the device index
//! shifts with USB enumeration order and must not invalidate the
//! calibration.

use std::path::{Path, PathBuf};

use tracing::{info, warn};

use crate::calibration::LOCKBAR_WIDTH_MM;

/// One hand-fixed calibration: annotated frame dimensions + the four lines.
#[derive(Debug, Clone, Copy)]
pub struct FixedAnchorEntry {
    pub img_w: u32,
    pub img_h: u32,
    /// `[sideleft, sideright, lockbar_player, lockbar_screen]`.
    pub lines: [anchor::LineSeg; 4],
}

/// Try both search locations for the given backend slug.
#[must_use]
pub fn load(
    slug: &str,
    vpx_path: Option<&Path>,
    pref_path: Option<&Path>,
) -> Option<FixedAnchorEntry> {
    let candidates: Vec<PathBuf> = [
        vpx_path.map(|p| {
            p.join("plugins")
                .join("headtracking")
                .join("anchor_fixed.json")
        }),
        pref_path.map(|p| p.join("anchor_fixed.json")),
    ]
    .into_iter()
    .flatten()
    .collect();
    for path in candidates {
        if let Some(entry) = load_from(&path, slug) {
            info!(?path, slug, "anchor_fixed.json: fixed calibration loaded");
            return Some(entry);
        }
    }
    None
}

fn load_from(path: &Path, slug: &str) -> Option<FixedAnchorEntry> {
    let text = std::fs::read_to_string(path).ok()?; // absent file = feature off
    let root: serde_json::Value = match serde_json::from_str(&text) {
        Ok(v) => v,
        Err(e) => {
            warn!(?path, "anchor_fixed.json unreadable: {e}");
            return None;
        }
    };
    let entry = root.get(slug).or_else(|| {
        slug.starts_with("webcam")
            .then(|| root.get("webcam"))
            .flatten()
    })?;
    let dim = |k: &str| entry.get(k).and_then(serde_json::Value::as_u64);
    let (Some(img_w), Some(img_h)) = (dim("img_w"), dim("img_h")) else {
        warn!(slug, "anchor_fixed.json entry missing img_w/img_h");
        return None;
    };
    // One line = [[x1, y1], [x2, y2]].
    let seg = |name: &str| -> Option<anchor::LineSeg> {
        let l = entry.get("lines")?.get(name)?;
        let p =
            |i: usize, j: usize| -> Option<f32> { l.get(i)?.get(j)?.as_f64().map(|v| v as f32) };
        Some([[p(0, 0)?, p(0, 1)?], [p(1, 0)?, p(1, 1)?]])
    };
    let names = ["sideleft", "sideright", "lockbar_player", "lockbar_screen"];
    let mut lines = [[[0.0f32; 2]; 2]; 4];
    for (dst, name) in lines.iter_mut().zip(names) {
        *dst = seg(name)?;
    }
    Some(FixedAnchorEntry {
        img_w: img_w as u32,
        img_h: img_h as u32,
        lines,
    })
}

/// Nominal colour-stream focal for a backend slug at the entry's frame
/// width — good enough for the diagnostic camera pose (the demo validated
/// these against tape measurements at ±0-3 %).
fn nominal_fx(slug: &str, img_w: u32, webcam_focal_px: f32) -> f32 {
    if slug.starts_with("kinect-v1") {
        525.0
    } else if slug.starts_with("kinect-v2") {
        1081.4
    } else if webcam_focal_px > 0.0 {
        webcam_focal_px
    } else {
        img_w as f32 * crate::tracker::pipeline::WEBCAM_FX_PER_WIDTH
    }
}

/// Derive the camera pose from a fixed calibration and format the
/// human-readable summary pushed as a VPX notification. `lockbar_mm = 0`
/// falls back to [`LOCKBAR_WIDTH_MM`].
#[must_use]
pub fn camera_pose_summary(
    slug: &str,
    entry: &FixedAnchorEntry,
    lockbar_mm: f32,
    webcam_focal_px: f32,
) -> Option<String> {
    let geom = anchor::geometry_from_lines(
        entry.lines[0],
        entry.lines[1],
        entry.lines[2],
        entry.lines[3],
        entry.img_w,
        entry.img_h,
    )?;
    let fx = nominal_fx(slug, entry.img_w, webcam_focal_px);
    let intr = anchor::CameraIntrinsics {
        fx,
        fy: fx,
        cx: entry.img_w as f32 * 0.5,
        cy: entry.img_h as f32 * 0.5,
    };
    let lockbar = if lockbar_mm > 0.0 {
        lockbar_mm
    } else {
        LOCKBAR_WIDTH_MM
    };
    let pose = anchor::camera_pose(&geom, &intr, lockbar)?;
    let approx = if slug.starts_with("webcam") { "~" } else { "" };
    Some(format!(
        "Head tracking: camera {approx}{:.2} m from the lockbar, {:.0} cm above, offset {:+.0} cm, tilted {:.0}\u{b0}",
        pose.distance_mm / 1000.0,
        pose.height_mm / 10.0,
        pose.lateral_mm / 10.0,
        pose.pitch_deg,
    ))
}
